name: Feature request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: ["jathavaan"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: When I have many tags, finding one in the autocomplete is slow.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, alternatives, links.
    validations:
      required: false
